version = "1.0"

[main]
name = "Font Compare settings"

    [main.default_colors]
    name = "Default colors"

        [main.default_colors.background]
        ask = "Default background color"
        type = "color"
        default = "#cccccc"

        [main.default_colors.font]
        ask = "Default font color"
        type = "color"
        default = "#000000"
