version = "1.0"

[main]
name = "Font Compare settings"

    [main.default_colors]
    name = "Default colors"

        [main.default_colors.background]
        ask = "Default background color"
        type = "color"
        default = "#cccccc"
        bind = "background_color:__INSTALL_DIR__/ynh_fontcompare_settings.yml"

        [main.default_colors.font]
        ask = "Default font color"
        type = "color"
        default = "#000000"
        bind = "font_color:__INSTALL_DIR__/ynh_fontcompare_settings.yml"
