#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================


source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEYS
#=================================================

get__background() {
    current_color=$(grep 'id="backgroundColorPicker' "$install_dir/index.html" | grep -oP 'value="\K[^"]*') # e.g. #cccccc
    echo "\"$current_color\""
    #echo $current_color # waiting for https://github.com/YunoHost-Apps/fontcompare_ynh/issues/1
}
get__font() {
    current_color=$(grep 'id="fontColorPicker' "$install_dir/index.html" | grep -oP 'value="\K[^"]*')       # e.g. #000000
    echo "\"$current_color\""
    #echo $current_color # waiting for https://github.com/YunoHost-Apps/fontcompare_ynh/issues/1
}

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

set__background() {
    current_color=$(grep 'id="backgroundColorPicker' "$install_dir/index.html" | grep -oP 'value="\K[^"]*')
    new_color=$background  
    ynh_replace --match=$current_color --replace=$new_color --file="$install_dir/index.html"
    sed -i -e "/$current_color/{s//$new_color/;:p" -e 'n;bp' -e '}' "$install_dir/css/style.css" #only first match (should be the one in body{})
}
set__font() {
    current_color=$(grep 'id="fontColorPicker' "$install_dir/index.html" | grep -oP 'value="\K[^"]*')
    new_color=$font
    ynh_replace --match=$current_color --replace=$new_color --file="$install_dir/index.html"
}

#=================================================
# GENERIC FINALIZATION
#=================================================

ynh_app_config_run $1
