#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEYS
#=================================================

get__background() {
    current_color=$(grep 'id="backgroundColorPicker' "$install_dir/index.html" | grep -oP 'value="\K[^"]*') # e.g. #cccccc
    echo $current_color
}
get__font() {
    current_color=$(grep 'id="fontColorPicker' "$install_dir/index.html" | grep -oP 'value="\K[^"]*')       # e.g. #000000
    echo $current_color
}

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

set__background() {
    current_color=$(grep 'id="backgroundColorPicker' "$install_dir/index.html" | grep -oP 'value="\K[^"]*')
    new_color=$background  
    ynh_replace --match=$current_color --replace=$new_color --file="$install_dir/index.html"
}
set__font() {
    current_color=$(grep 'id="fontColorPicker' "$install_dir/index.html" | grep -oP 'value="\K[^"]*')
    new_color=$font
    ynh_replace --match=$current_color --replace=$new_color --file="$install_dir/index.html"
}
