#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# SAVE CURRENT SETTINGS IN MEMORY 
#=================================================
saved_background_color=$(grep 'id="backgroundColorPicker' "$install_dir/index.html" | grep -oP 'value="\K[^"]*') # e.g. #cccccc
saved_font_color=$(grep 'id="fontColorPicker' "$install_dir/index.html" | grep -oP 'value="\K[^"]*')             # e.g. #000000

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."
	
ynh_setup_source --dest_dir="$install_dir" --full_replace

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

# Restore saved settings
reset_background_color=$(grep 'id="backgroundColorPicker' "$install_dir/index.html" | grep -oP 'value="\K[^"]*')
ynh_replace --match=$reset_background_color --replace=$saved_background_color --file="$install_dir/index.html"
sed -i -e "/$reset_background_color/{s//$saved_font_color/;:p" -e 'n;bp' -e '}' "$install_dir/css/style.css" #only first match (should be the one in body{})

reset_font_color=$(grep 'id="fontColorPicker' "$install_dir/index.html" | grep -oP 'value="\K[^"]*')
ynh_replace --match=$reset_font_color --replace=$saved_font_color --file="$install_dir/index.html"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Upgrade of $app completed"
